'use strict';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const money=n=>`${Math.round(Number(n)||0).toLocaleString('fr-FR')} FCFA`;const dateFr=v=>v?new Date(`${v}T12:00:00`).toLocaleDateString('fr-FR'):'—';
function values(){const labor=+$('labor').value||0,parts=+$('parts').value||0,advance=+$('advance').value||0,total=labor+parts;return {labor,parts,advance,total,balance:Math.max(0,total-advance)};}
function recalcRepair(){const v=values();$('totalRepair').value=money(v.total);}
function generateRepair(){const v=values();$('d-number').textContent=$('repairNumber').value||'BR-001';$('d-date').textContent=`Dépôt : ${dateFr($('depositDate').value)}`;$('d-client').textContent=$('clientName').value||'—';$('d-phone').textContent=$('clientPhone').value||'—';$('d-address').textContent=$('clientAddress').value||'—';$('d-tech').textContent=$('technician').value||'—';$('d-deposit').textContent=dateFr($('depositDate').value);$('d-return').textContent=dateFr($('returnDate').value);$('d-type').textContent=$('deviceType').value;$('d-model').textContent=$('deviceModel').value||'—';$('d-serial').textContent=$('serialNumber').value||'—';$('d-condition').textContent=$('deviceCondition').value;$('d-accessories').textContent=$('accessories').value||'Aucun indiqué';$('d-problem').textContent=$('problem').value||'Non renseigné';$('d-diagnosis').textContent=$('diagnosis').value||'À compléter';$('d-work').textContent=$('work').value||'À compléter';$('d-labor').textContent=money(v.labor);$('d-parts').textContent=money(v.parts);$('d-advance').textContent=money(v.advance);$('d-balance').textContent=money(v.balance);$('d-total').textContent=money(v.total);$('d-status').textContent=$('status').value;$('d-warranty').textContent=$('warranty').value;const notes=$('notes').value.trim();$('d-notes').innerHTML=notes?`<strong>Observations :</strong> ${esc(notes)}`:'';$('docInner').style.display='block';$('placeholder').style.display='none';$('docInner').scrollIntoView({behavior:'smooth',block:'start'});}
function printRepair(){if($('docInner').style.display==='none')generateRepair();setTimeout(()=>window.print(),120);}
function saveRepair(){const name=$('clientName').value.trim();if(!name){alert('Renseignez le nom du client.');return;}const v=values(),number=$('repairNumber').value||`BR-${Date.now()}`,list=JSON.parse(localStorage.getItem('samassa_bons_reparation')||'[]');if(list.some(x=>x.number===number)){alert('Ce bon existe déjà.');return;}list.push({number,date:$('depositDate').value,returnDate:$('returnDate').value,client:name,phone:$('clientPhone').value,address:$('clientAddress').value,technician:$('technician').value,device:{type:$('deviceType').value,model:$('deviceModel').value,serial:$('serialNumber').value,condition:$('deviceCondition').value,accessories:$('accessories').value},problem:$('problem').value,diagnosis:$('diagnosis').value,work:$('work').value,labor:v.labor,parts:v.parts,advance:v.advance,total:v.total,balance:v.balance,status:$('status').value,warranty:$('warranty').value,notes:$('notes').value,timestamp:new Date().toISOString()});localStorage.setItem('samassa_bons_reparation',JSON.stringify(list));if(window.ST?.toast)ST.toast(`Bon ${number} enregistré ✓`,'success');else alert('Bon de réparation enregistré.');$('repairNumber').value=`BR-${String(list.length+1).padStart(3,'0')}`;}
function shareRepairWhatsApp(){if($('docInner').style.display==='none')generateRepair();const v=values(),msg=`*SAMASSA TECHNOLOGIE*\nBon de réparation N° ${$('repairNumber').value}\nClient : ${$('clientName').value}\nAppareil : ${$('deviceType').value} ${$('deviceModel').value}\nPanne : ${$('problem').value||'À diagnostiquer'}\nTotal estimatif : ${money(v.total)}\nStatut : ${$('status').value}\nTéléphone : 77 29 19 31 / 62 97 06 30`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,'_blank');}
document.addEventListener('DOMContentLoaded',()=>{const now=new Date();$('depositDate').value=now.toISOString().slice(0,10);const ret=new Date(now);ret.setDate(ret.getDate()+3);$('returnDate').value=ret.toISOString().slice(0,10);recalcRepair();});
