'use strict';
let saleItems = [];
const el = id => document.getElementById(id);
const fmt = n => `${Math.round(Number(n)||0).toLocaleString('fr-FR')} FCFA`;
const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function addSaleItem(data={}) {
  const row=document.createElement('div'); row.className='item-row';
  row.innerHTML=`<div class="item-inputs"><input type="text" placeholder="Description de l’article ou service" value="${esc(data.desc||'')}" oninput="recalcSale()"><input type="number" placeholder="Qté" value="${data.qty||1}" min="1" oninput="recalcSale()"><input type="number" placeholder="Prix unitaire" value="${data.price||0}" min="0" oninput="recalcSale()"><input type="number" placeholder="Total" readonly></div><button class="remove-btn" type="button" onclick="removeSaleItem(this)">✕</button>`;
  el('saleItems').appendChild(row); recalcSale();
}
function removeSaleItem(btn){const rows=document.querySelectorAll('#saleItems .item-row');if(rows.length<=1){alert('Gardez au moins une ligne.');return;}btn.closest('.item-row').remove();recalcSale();}
function collectSale(){let subtotal=0;const items=[...document.querySelectorAll('#saleItems .item-row')].map(row=>{const i=row.querySelectorAll('input'),qty=+i[1].value||0,price=+i[2].value||0,total=qty*price; i[3].value=total;subtotal+=total;return {desc:i[0].value.trim()||'Article ou service',qty,price,total};});const discount=+el('discount').value||0;const total=Math.max(0,subtotal-discount);return {items,subtotal,discount,total,received:+el('received').value||0,change:Math.max(0,(+el('received').value||0)-total)};}
function recalcSale(){const d=collectSale();el('totalAmount').value=fmt(d.total);el('changeAmount').value=fmt(d.change);}
function generateSaleReceipt(){const d=collectSale(),client=el('clientName').value.trim()||'Client comptoir';el('d-num').textContent=el('receiptNumber').value||'RV-001';el('d-date').textContent=el('receiptDate').value?new Date(`${el('receiptDate').value}T12:00:00`).toLocaleDateString('fr-FR'):'—';el('d-client').textContent=client;el('d-client-details').textContent=[el('clientPhone').value,el('clientAddress').value].filter(Boolean).join(' · ')||'—';el('d-operation').textContent=el('operationType').value;el('d-payment').textContent=el('paymentMethod').value;el('d-received').textContent=fmt(d.received);el('d-change').textContent=fmt(d.change);el('d-total').textContent=fmt(d.total);el('d-items').innerHTML=d.items.map(i=>`<tr><td>${esc(i.desc)}</td><td>${i.qty}</td><td>${fmt(i.price)}</td><td>${fmt(i.total)}</td></tr>`).join('');const notes=el('notes').value.trim();el('d-notes').style.display=notes?'block':'none';el('d-notes').innerHTML=notes?`<strong>Notes :</strong> ${esc(notes)}`:'';el('docInner').style.display='block';el('placeholder').style.display='none';el('docInner').scrollIntoView({behavior:'smooth',block:'start'});}
function printSaleReceipt(){if(el('docInner').style.display==='none')generateSaleReceipt();setTimeout(()=>window.print(),120);}
function saveSaleReceipt(){const d=collectSale();if(!d.total){alert('Ajoutez un montant avant d’enregistrer.');return;}if(el('docInner').style.display==='none')generateSaleReceipt();const number=el('receiptNumber').value||`RV-${Date.now()}`;const list=JSON.parse(localStorage.getItem('samassa_recus_vente')||'[]');if(list.some(x=>x.number===number)){alert('Ce reçu existe déjà.');return;}const record={number,date:el('receiptDate').value,client:el('clientName').value||'Client comptoir',phone:el('clientPhone').value,operation:el('operationType').value,total:d.total,received:d.received,change:d.change,payment:el('paymentMethod').value,items:d.items,notes:el('notes').value,timestamp:new Date().toISOString(),statut:'Payé'};list.push(record);localStorage.setItem('samassa_recus_vente',JSON.stringify(list));const caisse=JSON.parse(localStorage.getItem('samassa_mouvements')||'[]');caisse.push({id:Date.now(),date:el('receiptDate').value,type:'entree',desc:`${record.operation} · ${number}`,amount:d.total,pm:record.payment,cat:'Vente / encaissement',auto:true,timestamp:new Date().toISOString()});localStorage.setItem('samassa_mouvements',JSON.stringify(caisse));if(window.ST?.toast)ST.toast(`Reçu ${number} enregistré en caisse ✓`,'success');else alert('Reçu enregistré en caisse.');el('receiptNumber').value=`RV-${String(list.length+1).padStart(3,'0')}`;}
function shareSaleWhatsApp(){if(el('docInner').style.display==='none')generateSaleReceipt();const d=collectSale(),msg=`*SAMASSA TECHNOLOGIE*\nReçu de vente N° ${el('receiptNumber').value}\nClient : ${el('clientName').value||'Client comptoir'}\nOpération : ${el('operationType').value}\nTotal : *${fmt(d.total)}*\nPaiement : ${el('paymentMethod').value}\n\nMerci pour votre confiance !\n77 29 19 31 / 62 97 06 30`;window.open(`https://wa.me/?text=${encodeURIComponent(msg)}`,'_blank');}
document.addEventListener('DOMContentLoaded',()=>{el('receiptDate').value=new Date().toISOString().slice(0,10);recalcSale();});
